ALTER TABLE DBO.Residential
ADD PrivateRoom	int,
SemiPrivateRoom	int,
ResEmpNurs	Decimal(18,2), 
ResStaffNurs	Decimal(18,2), 
ResEmpNursPract	Decimal(18,2), 
ResStaffNursPract	Decimal(18,2), 
ResEmpSS	Decimal(18,2), 
ResStaffSS	Decimal(18,2), 
ResEmpHHA	Decimal(18,2), 
ResStaffHHA	Decimal(18,2), 
ResEmpPhy	Decimal(18,2), 
ResStaffPhy	Decimal(18,2), 
ResEmpPhyVol	Decimal(18,2), 
ResStaffPhyVol	Decimal(18,2), 
ResEmpChap	Decimal(18,2), 
ResStaffChap	Decimal(18,2), 
ResEmpOth	Decimal(18,2), 
ResStaffOth	Decimal(18,2), 
ResEmpNon	Decimal(18,2), 
ResStaffNon	Decimal(18,2), 
ResEmpTotal	Decimal(18,2), 
ResStaffTotal	Decimal(18,2), 
ResFTETotal	Decimal(18,2) 
