ALTER TABLE DBO.Inpatient
ADD EmpNursing	Decimal(18,2), 
StaffNursing	Decimal(18,2), 
EmpNursingPract	Decimal(18,2), 
StaffNursingPract	Decimal(18,2), 
EmpSocialServ	Decimal(18,2), 
StaffSocialServ	Decimal(18,2), 
EmpHHA	Decimal(18,2), 
StaffHHA	Decimal(18,2), 
EmpMD	Decimal(18,2), 
StaffMD	Decimal(18,2), 
EmpMDVol	Decimal(18,2), 
StaffMDVol	Decimal(18,2), 
EmpChap	Decimal(18,2), 
StaffChap	Decimal(18,2), 
EmpOtherClinical	Decimal(18,2), 
StaffOtherClinical	Decimal(18,2), 
EmpNonClinical	Decimal(18,2), 
StaffNonClinical	Decimal(18,2), 
EmpTotal	Decimal(18,2), 
StaffTotal	Decimal(18,2), 
FTETotal	Decimal(18,2) 
