ALTER TABLE DBO.survey
ADD BehavHealthAdmitPY	INT, 
BehavHealthAdmitCY	INT, 
WoundCareAdmitPY	INT, 
WoundCareAdmitCY	INT, 
ComSocialAdmitPY	INT, 
ComSocialAdmitCY	INT, 
InfectionAdmitPY	INT, 
InfectionAdmitCY	INT, 
OxyDependAdmitPY	INT, 
OxyDependAdmitCY	INT, 
AggBehavAdmitPY	INT, 
AggBehavAdmitCY	INT, 
InfuMedAdmitPY	INT, 
InfuMedAdmitCY	INT, 
DialysisAdmitPY	INT, 
DialysisAdmitCY	INT, 
TotalAdmitPY	INT, 
TotalAdmitCY	INT, 
DirectPatientStaffPY	INT, 
DirectPatientStaffHrsPY	Decimal(18,1), 
DirectPatientStaffCY	INT, 
DirectPatientStaffHrsCY	Decimal(18,1), 
ClinicalStaffPY	INT, 
ClinicalStaffHrsPY	Decimal(18,1), 
ClinicalStaffCY	INT, 
ClinicalStaffHrsCY	Decimal(18,1), 
GeneralStaffPY	INT, 
GeneralStaffHrsPY	Decimal(18,1), 
GeneralStaffCY	INT, 
GeneralStaffHrsCY	Decimal(18,1), 
TotalOnCallStaffPY	INT, 
TotalOnCallStaffHrsPY	Decimal(18,1), 
TotalOnCallStaffCY	INT, 
TotalOnCallStaffHrsCY	Decimal(18,1), 
PainMgtPY	INT NOT NULL DEFAULT 0,
PainMgtCY	INT NOT NULL DEFAULT 0,
NursingVisitPY	INT NOT NULL DEFAULT 0,
NursingVisitCY	INT NOT NULL DEFAULT 0,
HospiceAidePY	INT NOT NULL DEFAULT 0,
HospiceAideCY	INT NOT NULL DEFAULT 0,
MedicalSocialPY	INT NOT NULL DEFAULT 0,
MedicalSocialCY	INT NOT NULL DEFAULT 0,
SpiritualPY	INT NOT NULL DEFAULT 0,
SpiritualCY	INT NOT NULL DEFAULT 0,
BereavementPY	INT NOT NULL DEFAULT 0,
BereavementCY	INT NOT NULL DEFAULT 0,
MedEquipPY	INT NOT NULL DEFAULT 0,
MedEquipCY	INT NOT NULL DEFAULT 0,
MedDeliveryPY	INT NOT NULL DEFAULT 0,
MedDeliveryCY	INT NOT NULL DEFAULT 0,
TherapeuticPY	INT NOT NULL DEFAULT 0,
TherapeuticCY	INT NOT NULL DEFAULT 0,
TotalOtherSevPY	INT NOT NULL DEFAULT 0,
TotalOtherSevCY	INT NOT NULL DEFAULT 0,
TotStaffingDirNursing	Decimal(18,1), 
TotStaffingIndNursing	Decimal(18,1), 
TotStaffingPractNursing	Decimal(18,1), 
TotStaffingSocial	Decimal(18,1), 
TotStaffingHHA	Decimal(18,1), 
TotStaffingMD	Decimal(18,1), 
TotStaffingMDVol	Decimal(18,1), 
TotStaffingChap	Decimal(18,1), 
TotStaffingOtherClinical	Decimal(18,1), 
TotStaffingBereavement	Decimal(18,1), 
TotStaffingClinical	Decimal(18,1), 
TotStaffingNonClinical	Decimal(18,1), 
TotStaffingTotal	Decimal(18,1), 
MedDirectorPY	VARCHAR(100),
MedDirectorCY	VARCHAR(100),
AdminPY	VARCHAR(100),
AdminCY	VARCHAR(100),
MedicareRevPY	Decimal(18,2), 
MedicareExpPY	Decimal(18,2), 
MedicareRevCY	Decimal(18,2), 
MedicareExpCY	Decimal(18,2), 
MedicaidRevPY	Decimal(18,2), 
MedicaidExpPY	Decimal(18,2), 
MedicaidRevCY	Decimal(18,2), 
MedicaidExpCY	Decimal(18,2), 
InsRevPY	Decimal(18,2), 
InsExpPY	Decimal(18,2), 
InsRevCY	Decimal(18,2), 
InsExpCY	Decimal(18,2), 
SelfPayRevPY	Decimal(18,2), 
SelfPayExpPY	Decimal(18,2), 
SelfPayRevCY	Decimal(18,2), 
SelfPayExpCY	Decimal(18,2), 
OthGovtRevPY	Decimal(18,2), 
OthGovtExpPY	Decimal(18,2), 
OthGovtRevCY	Decimal(18,2), 
OthGovtExpCY	Decimal(18,2), 
TotalHospServRevPY	Decimal(18,2), 
TotalHospServExpPY	Decimal(18,2), 
TotalHospServRevCY	Decimal(18,2), 
TotalHospServExpCY	Decimal(18,2), 
TotalAgFundRevPY	Decimal(18,2), 
TotalAgFundExpPY	Decimal(18,2), 
TotalAgFundRevCY	Decimal(18,2), 
TotalAgFundExpCY	Decimal(18,2), 
TotalOtherRevPY	Decimal(18,2), 
TotalOtherExpPY	Decimal(18,2), 
TotalOtherRevCY	Decimal(18,2), 
TotalOtherExpCY	Decimal(18,2), 
TotalCharityRevPY	Decimal(18,2), 
TotalCharityExpPY	Decimal(18,2), 
TotalCharityRevCY	Decimal(18,2), 
TotalCharityExpCY	Decimal(18,2), 
TotalStaffEduExpPY	Decimal(18,2), 
TotalStaffEduExpCY	Decimal(18,2), 
TotalNoInsExpPY	Decimal(18,2), 
TotalNoInsExpCY	Decimal(18,2), 
TotalOverExpPY	Decimal(18,2), 
TotalOverExpCY	Decimal(18,2), 
GrandTotalRevPY	Decimal(18,2), 
GrandTotalExpPY	Decimal(18,2), 
GrandTotalRevCY	Decimal(18,2), 
GrandTotalExpCY	Decimal(18,2), 
FinCashPY	Decimal(18,2), 
FinCashCY	Decimal(18,2), 
FinTotalRevPY	Decimal(18,2), 
FinTotalRevCY	Decimal(18,2), 
FinTotalExpPY	Decimal(18,2), 
FinTotalExpCY	Decimal(18,2), 
FinBadDebtPY	Decimal(18,2), 
FinBadDebtCY	Decimal(18,2), 
FinNetIncomePY	Decimal(18,2), 
FinNetIncomeCY	Decimal(18,2), 
FinDebtCoverRatioPY	Decimal(18,2), 
FinDebtCoverRatioCY	Decimal(18,2), 
FinAdjEBITDAPY	Decimal(18,2), 
FinAdjEBITDACY	Decimal(18,2), 
PalMedicareRevPY	Decimal(18,2), 
PalMedicareExpPY	Decimal(18,2), 
PalMedicareRevCY	Decimal(18,2), 
PalMedicareExpCY	Decimal(18,2), 
PalMedicaidRevPY	Decimal(18,2), 
PalMedicaidExpPY	Decimal(18,2), 
PalMedicaidRevCY	Decimal(18,2), 
PalMedicaidExpCY	Decimal(18,2), 
PalInsRevPY	Decimal(18,2), 
PalInsExpPY	Decimal(18,2), 
PalInsRevCY	Decimal(18,2), 
PalInsExpCY	Decimal(18,2), 
PalSelfPayRevPY	Decimal(18,2), 
PalSelfPayExpPY	Decimal(18,2), 
PalSelfPayRevCY	Decimal(18,2), 
PalSelfPayExpCY	Decimal(18,2), 
PalOthGovtRevPY	Decimal(18,2), 
PalOthGovtExpPY	Decimal(18,2), 
PalOthGovtRevCY	Decimal(18,2), 
PalOthGovtExpCY	Decimal(18,2), 
PalTotalHospServRevPY	Decimal(18,2), 
PalTotalHospServExpPY	Decimal(18,2), 
PalTotalHospServRevCY	Decimal(18,2), 
PalTotalHospServExpCY	Decimal(18,2)
