Imports System.Data
Imports System.Data.SqlClient
Imports Mhcc.Hospice
Partial Class Report_Part2
    'Inherits System.Web.UI.Page
    Inherits BasePage
    Public CurrentYear As String = GetYear()
    Public PreviousYear As String = GetYear() - 1
    Public currencyFormat As String = "$#,##0.00;($#,##0.00);$0.00"
    Protected Overloads Sub Page_Load(sender As Object, e As System.EventArgs) Handles Me.Load
        If Not IsPostBack Then
            'Changed following code - JS
            'Dim cookie As HttpCookie
            'cookie = Request.Cookies.Get("Hospiceusersettings")

            If Len(Request.QueryString("username") & "") > 0 Then
                UserName.Text = Request.QueryString("username")
                lblFirstname.Text = Request.QueryString("firstName")
                lblLastName.Text = ", Review by MHCC " & " " & FormatDateTime(Today)
            Else
                'If (cookie Is Nothing) Then
                '    Response.Redirect("noaccess.html")
                'Else
                '    UserName.Text = Request.Cookies("Hospiceusersettings")("UserName")
                '    lblFirstname.Text = Request.Cookies("Hospiceusersettings")("FirstName")
                '    lblLastName.Text = Request.Cookies("Hospiceusersettings")("LastName")
                'End If
                UserName.Text = GetUserName()
                lblFirstname.Text = GetFirstName()
                lblLastName.Text = GetLastName()
            End If


            SY0.Text = GetYear()
            SY1.Text = GetYear()
            SY2.Text = GetYear()
            SY3.Text = GetYear()
            SY4.Text = GetYear()
            SY5.Text = GetYear()

            '------------------------------------------------------------------------------
            '------------------------------------------------------------------------------
            LoadSurveySectionF5()
            LoadSurveySectionG()
            LoadComments()
            LoadCert()
        End If
    End Sub

    Sub LoadSurveySectionF5()
        'Commented code - 03/08
        'Dim strSQL As String
        'Dim con As New SqlConnection(ConfigurationManager.ConnectionStrings("ConnectionString").ConnectionString)
        'con.Open()
        'strSQL = "Select * FROM Costs where UserName='" & UserName.Text & "'"
        'Dim cmd As New SqlCommand(strSQL, con)
        'Dim DBReader = cmd.ExecuteReader()
        Dim costsDB As CostsDBLayer = New CostsDBLayer()
        Dim DBReader = costsDB.GetCosts("Select * FROM Costs where UserName='" & UserName.Text & "'")
        While DBReader.Read()

            If Len(DBReader("_1BldgFixA10") & "") > 0 Then _1BldgFixA10.Text = DBReader("_1BldgFixA10")
            If Len(DBReader("_2MovEquipA10") & "") > 0 Then _2MovEquipA10.Text = DBReader("_2MovEquipA10")
            If Len(DBReader("_54EmpBenefitsA10") & "") > 0 Then _54EmpBenefitsA10.Text = DBReader("_54EmpBenefitsA10")
            If Len(DBReader("_6AGA10") & "") > 0 Then _6AGA10.Text = DBReader("_6AGA10")
            If Len(DBReader("_3PlantOpA10") & "") > 0 Then _3PlantOpA10.Text = DBReader("_3PlantOpA10")
            If Len(DBReader("_55LLServA10") & "") > 0 Then _55LLServA10.Text = DBReader("_55LLServA10")
            If Len(DBReader("_56hkeepingA10") & "") > 0 Then _56hkeepingA10.Text = DBReader("_56hkeepingA10")
            If Len(DBReader("_57DietaryA10") & "") > 0 Then _57DietaryA10.Text = DBReader("_57DietaryA10")
            If Len(DBReader("_57DietaryB7") & "") > 0 Then _57DietaryB7.Text = DBReader("_57DietaryB7")
            If Len(DBReader("_58NursAdmA10") & "") > 0 Then _58NursAdmA10.Text = DBReader("_58NursAdmA10")
            If Len(DBReader("_58NursAdmB7") & "") > 0 Then _58NursAdmB7.Text = DBReader("_58NursAdmB7")
            If Len(DBReader("_59RMSA10") & "") > 0 Then _59RMSA10.Text = DBReader("_59RMSA10")
            If Len(DBReader("_59RMSAB7") & "") > 0 Then _59RMSAB7.Text = DBReader("_59RMSAB7")

            If Len(DBReader("_60MedRecA10") & "") > 0 Then _60MedRecA10.Text = DBReader("_60MedRecA10")
            If Len(DBReader("_60MedRecB7") & "") > 0 Then _60MedRecB7.Text = DBReader("_60MedRecB7")
            If Len(DBReader("_61TransStaffA10") & "") > 0 Then _61TransStaffA10.Text = DBReader("_61TransStaffA10")
            If Len(DBReader("_61TransStaffB7") & "") > 0 Then _61TransStaffB7.Text = DBReader("_61TransStaffB7")
            If Len(DBReader("_62VolServA10") & "") > 0 Then _62VolServA10.Text = DBReader("_62VolServA10")
            If Len(DBReader("_62VolServB7") & "") > 0 Then _62VolServB7.Text = DBReader("_62VolServB7")
            If Len(DBReader("_63PharmA10") & "") > 0 Then _63PharmA10.Text = DBReader("_63PharmA10")
            If Len(DBReader("_63PharmB7") & "") > 0 Then _63PharmB7.Text = DBReader("_63PharmB7")
            If Len(DBReader("_64MDASA10") & "") > 0 Then _64MDASA10.Text = DBReader("_64MDASA10")
            If Len(DBReader("_64MDASB7") & "") > 0 Then _64MDASB7.Text = DBReader("_64MDASB7")
            If Len(DBReader("_65OAGServOther") & "") > 0 Then _65OAGServOther.Text = DBReader("_65OAGServOther")
            If Len(DBReader("_65OAGServA10") & "") > 0 Then _65OAGServA10.Text = DBReader("_65OAGServA10")
            If Len(DBReader("_65OAGServB7") & "") > 0 Then _65OAGServB7.Text = DBReader("_65OAGServB7")
            If Len(DBReader("_66PRCServsA10") & "") > 0 Then _66PRCServsA10.Text = DBReader("_66PRCServsA10")
            If Len(DBReader("_66PRCServsB7") & "") > 0 Then _66PRCServsB7.Text = DBReader("_66PRCServsB7")

            If Len(DBReader("_67IPCareA10") & "") > 0 Then _67IPCareA10.Text = DBReader("_67IPCareA10")
            If Len(DBReader("_67IPCareB7") & "") > 0 Then _67IPCareB7.Text = DBReader("_67IPCareB7")
            If Len(DBReader("_15MDAA10") & "") > 0 Then _15MDAA10.Text = DBReader("_15MDAA10")
            If Len(DBReader("_15MDAB7") & "") > 0 Then _15MDAB7.Text = DBReader("_15MDAB7")
            If Len(DBReader("_67NursPractA10") & "") > 0 Then _67NursPractA10.Text = DBReader("_67NursPractA10")
            If Len(DBReader("_67NursPractB7") & "") > 0 Then _67NursPractB7.Text = DBReader("_67NursPractB7")
            If Len(DBReader("_68RegNursA10") & "") > 0 Then _68RegNursA10.Text = DBReader("_68RegNursA10")
            If Len(DBReader("_68RegNursB7") & "") > 0 Then _68RegNursB7.Text = DBReader("_68RegNursB7")

            If Len(DBReader("_69LPVNA10") & "") > 0 Then _69LPVNA10.Text = DBReader("_69LPVNA10")
            If Len(DBReader("_69LPVNB7") & "") > 0 Then _69LPVNB7.Text = DBReader("_69LPVNB7")
            If Len(DBReader("_17PTAA10") & "") > 0 Then _17PTAA10.Text = DBReader("_17PTAA10")
            If Len(DBReader("_17PTAB7") & "") > 0 Then _17PTAB7.Text = DBReader("_17PTAB7")
            If Len(DBReader("_18OTA10") & "") > 0 Then _18OTA10.Text = DBReader("_18OTA10")
            If Len(DBReader("_18OTB7") & "") > 0 Then _18OTB7.Text = DBReader("_18OTB7")
            If Len(DBReader("_19SLPA10") & "") > 0 Then _19SLPA10.Text = DBReader("_19SLPA10")
            If Len(DBReader("_19SLPB7") & "") > 0 Then _19SLPB7.Text = DBReader("_19SLPB7")
            If Len(DBReader("_20MedSSA10") & "") > 0 Then _20MedSSA10.Text = DBReader("_20MedSSA10")
            If Len(DBReader("_20MedSSB7") & "") > 0 Then _20MedSSB7.Text = DBReader("_20MedSSB7")
            If Len(DBReader("_21ChapA10") & "") > 0 Then _21ChapA10.Text = DBReader("_21ChapA10")
            If Len(DBReader("_21ChapB7") & "") > 0 Then _21ChapB7.Text = DBReader("_21ChapB7")
            If Len(DBReader("_22DietA10") & "") > 0 Then _22DietA10.Text = DBReader("_22DietA10")
            If Len(DBReader("_22DietB7") & "") > 0 Then _22DietB7.Text = DBReader("_22DietB7")
            If Len(DBReader("_23OtherCounsA10") & "") > 0 Then _23OtherCounsA10.Text = DBReader("_23OtherCounsA10")
            If Len(DBReader("_23OtherCounsB7") & "") > 0 Then _23OtherCounsB7.Text = DBReader("_23OtherCounsB7")
            If Len(DBReader("_70HAHSA10") & "") > 0 Then _70HAHSA10.Text = DBReader("_70HAHSA10")
            If Len(DBReader("_70HAHSB7") & "") > 0 Then _70HAHSB7.Text = DBReader("_70HAHSB7")
            If Len(DBReader("_30RxBioInfA10") & "") > 0 Then _30RxBioInfA10.Text = DBReader("_30RxBioInfA10")
            If Len(DBReader("_30RxBioInfB7") & "") > 0 Then _30RxBioInfB7.Text = DBReader("_30RxBioInfB7")

            If Len(DBReader("_32PtTransA10") & "") > 0 Then _32PtTransA10.Text = DBReader("_32PtTransA10")
            If Len(DBReader("_32PtTransB7") & "") > 0 Then _32PtTransB7.Text = DBReader("_32PtTransB7")
            If Len(DBReader("_33ImagA10") & "") > 0 Then _33ImagA10.Text = DBReader("_33ImagA10")
            If Len(DBReader("_33ImagB7") & "") > 0 Then _33ImagB7.Text = DBReader("_33ImagB7")
            If Len(DBReader("_34LabDiagA10") & "") > 0 Then _34LabDiagA10.Text = DBReader("_34LabDiagA10")
            If Len(DBReader("_34LabDiagB7") & "") > 0 Then _34LabDiagB7.Text = DBReader("_34LabDiagB7")
            If Len(DBReader("_35MedSupA10") & "") > 0 Then _35MedSupA10.Text = DBReader("_35MedSupA10")
            If Len(DBReader("_35MedSupB7") & "") > 0 Then _35MedSupB7.Text = DBReader("_35MedSupB7")
            If Len(DBReader("_36OPA10") & "") > 0 Then _36OPA10.Text = DBReader("_36OPA10")
            If Len(DBReader("_36OPB7") & "") > 0 Then _36OPB7.Text = DBReader("_36OPB7")
            If Len(DBReader("_71PRTA10") & "") > 0 Then _71PRTA10.Text = DBReader("_71PRTA10")
            If Len(DBReader("_71PRTB7") & "") > 0 Then _71PRTB7.Text = DBReader("_71PRTB7")
            If Len(DBReader("_72PallChemoA10") & "") > 0 Then _72PallChemoA10.Text = DBReader("_72PallChemoA10")
            If Len(DBReader("_72PallChemoB7") & "") > 0 Then _72PallChemoB7.Text = DBReader("_72PallChemoB7")
            If Len(DBReader("_73OPCSA10") & "") > 0 Then _73OPCSA10.Text = DBReader("_73OPCSA10")
            If Len(DBReader("_73OPCSB7") & "") > 0 Then _73OPCSB7.Text = DBReader("_73OPCSB7")
            If Len(DBReader("_73OPCSOther") & "") > 0 Then _73OPCSOther.Text = DBReader("_73OPCSOther")
            If Len(DBReader("_50BereavA10") & "") > 0 Then _50BereavA10.Text = DBReader("_50BereavA10")
            If Len(DBReader("_50BereavB7") & "") > 0 Then _50BereavB7.Text = DBReader("_50BereavB7")
            If Len(DBReader("_51VolA10") & "") > 0 Then _51VolA10.Text = DBReader("_51VolA10")
            If Len(DBReader("_51VolB7") & "") > 0 Then _51VolB7.Text = DBReader("_51VolB7")
            If Len(DBReader("_52FundraisA10") & "") > 0 Then _52FundraisA10.Text = DBReader("_52FundraisA10")
            If Len(DBReader("_52FundraisB7") & "") > 0 Then _52FundraisB7.Text = DBReader("_52FundraisB7")
            If Len(DBReader("_74HPMFA10") & "") > 0 Then _74HPMFA10.Text = DBReader("_74HPMFA10")
            If Len(DBReader("_74HPMFB7") & "") > 0 Then _74HPMFB7.Text = DBReader("_74HPMFB7")
            If Len(DBReader("_75PCPA10") & "") > 0 Then _75PCPA10.Text = DBReader("_75PCPA10")
            If Len(DBReader("_75PCPB7") & "") > 0 Then _75PCPB7.Text = DBReader("_75PCPB7")
            If Len(DBReader("_76MDASA10") & "") > 0 Then _76MDASA10.Text = DBReader("_76MDASA10")
            If Len(DBReader("_76MDASB7") & "") > 0 Then _76MDASB7.Text = DBReader("_76MDASB7")
            If Len(DBReader("_77ResCareA10") & "") > 0 Then _77ResCareA10.Text = DBReader("_77ResCareA10")
            If Len(DBReader("_77ResCareB7") & "") > 0 Then _77ResCareB7.Text = DBReader("_77ResCareB7")
            If Len(DBReader("_78Advert10") & "") > 0 Then _78Advert10.Text = DBReader("_78Advert10")
            If Len(DBReader("_78AdvertB7") & "") > 0 Then _78AdvertB7.Text = DBReader("_78AdvertB7")
            If Len(DBReader("_79THTMA10") & "") > 0 Then _79THTMA10.Text = DBReader("_79THTMA10")
            If Len(DBReader("_79THTMB7") & "") > 0 Then _79THTMB7.Text = DBReader("_79THTMB7")
            If Len(DBReader("_80thriftStA10") & "") > 0 Then _80thriftStA10.Text = DBReader("_80thriftStA10")
            If Len(DBReader("_80thriftStB7") & "") > 0 Then _80thriftStB7.Text = DBReader("_80thriftStB7")
            If Len(DBReader("_81NursFacRmA10") & "") > 0 Then _81NursFacRmA10.Text = DBReader("_81NursFacRmA10")
            If Len(DBReader("_81NursFacRmB7") & "") > 0 Then _81NursFacRmB7.Text = DBReader("_81NursFacRmB7")
            If Len(DBReader("_82NonReimbOtherA10") & "") > 0 Then _82NonReimbOtherA10.Text = DBReader("_82NonReimbOtherA10")
            If Len(DBReader("_82NonReimbOtherB7") & "") > 0 Then _82NonReimbOtherB7.Text = DBReader("_82NonReimbOtherB7")
            If Len(DBReader("_82NonReimbOther") & "") > 0 Then _82NonReimbOther.Text = DBReader("_82NonReimbOther")
            'If Len(DBReader("_71Other") & "") > 0 Then _71Other.Text = DBReader("_71Other")
            If Len(DBReader("_83ContHomeCareA10") & "") > 0 Then _83ContHomeCareA10.Text = DBReader("_83ContHomeCareA10")
            If Len(DBReader("_83ContHomeCareB7") & "") > 0 Then _83ContHomeCareB7.Text = DBReader("_83ContHomeCareB7")
            If Len(DBReader("_84RoutHomeCareA10") & "") > 0 Then _84RoutHomeCareA10.Text = DBReader("_84RoutHomeCareA10")
            If Len(DBReader("_84RoutHomeCareB7") & "") > 0 Then _84RoutHomeCareB7.Text = DBReader("_84RoutHomeCareB7")
            If Len(DBReader("_85InpatRespA10") & "") > 0 Then _85InpatRespA10.Text = DBReader("_85InpatRespA10")
            If Len(DBReader("_85InpatRespB7") & "") > 0 Then _85InpatRespB7.Text = DBReader("_85InpatRespB7")
            If Len(DBReader("_86GenRespA10") & "") > 0 Then _86GenRespA10.Text = DBReader("_86GenRespA10")
            If Len(DBReader("_86GenRespB7") & "") > 0 Then _86GenRespB7.Text = DBReader("_86GenRespB7")
            If Len(DBReader("_100TotalCostsA10") & "") > 0 Then _100TotalCostsA10.Text = DBReader("_100TotalCostsA10")
            If Len(DBReader("_100TotalCostsB7") & "") > 0 Then _100TotalCostsB7.Text = DBReader("_100TotalCostsB7")
            If Len(DBReader("CostRptRouHomeCare") & "") > 0 Then CostRptRouHomeCare.Text = DBReader("CostRptRouHomeCare")
            If Len(DBReader("CostRptGIDays") & "") > 0 Then CostRptGIDays.Text = DBReader("CostRptGIDays")
            If Len(DBReader("CostRPTRespiteDays") & "") > 0 Then CostRPTRespiteDays.Text = DBReader("CostRPTRespiteDays")
            If Len(DBReader("CostRPTTotHosDays") & "") > 0 Then CostRPTTotHosDays.Text = DBReader("CostRPTTotHosDays")
            If Len(DBReader("CostRptContHomeCare") & "") > 0 Then CostRptContHomeCare.Text = DBReader("CostRptContHomeCare")
            If Len(DBReader("totPallCareVisits") & "") > 0 Then totPallCareVisits.Text = DBReader("totPallCareVisits")
            'If Len(DBReader("totPallCareRev") & "") > 0 Then totPallCareRev.Text = DBReader("totPallCareRev")
            'F7. CONTRACT PER DIEM July 17 2026
            SetTextBoxValue(DBReader("FTENursingPY"), FTENursingPY)
            SetTextBoxValue(DBReader("CostNursingPY"), CostNursingPY)
            SetTextBoxValue(DBReader("FTENursingCY"), FTENursingCY)
            SetTextBoxValue(DBReader("CostNursingCY"), CostNursingCY)
            SetTextBoxValue(DBReader("FTENursingPractPY"), FTENursingPractPY)
            SetTextBoxValue(DBReader("CostNursingPractPY"), CostNursingPractPY)
            SetTextBoxValue(DBReader("FTENursingPractCY"), FTENursingPractCY)
            SetTextBoxValue(DBReader("CostNursingPractCY"), CostNursingPractCY)
            SetTextBoxValue(DBReader("FTESocialServPY"), FTESocialServPY)
            SetTextBoxValue(DBReader("CostSocialServPY"), CostSocialServPY)
            SetTextBoxValue(DBReader("FTESocialServCY"), FTESocialServCY)
            SetTextBoxValue(DBReader("CostSocialServCY"), CostSocialServCY)
            SetTextBoxValue(DBReader("FTEHospAidePY"), FTEHospAidePY)
            SetTextBoxValue(DBReader("CostHospAidePY"), CostHospAidePY)
            SetTextBoxValue(DBReader("FTEHospAideCY"), FTEHospAideCY)
            SetTextBoxValue(DBReader("CostHospAideCY"), CostHospAideCY)
            SetTextBoxValue(DBReader("FTEMDPY"), FTEMDPY)
            SetTextBoxValue(DBReader("CostMDPY"), CostMDPY)
            SetTextBoxValue(DBReader("FTEMDCY"), FTEMDCY)
            SetTextBoxValue(DBReader("CostMDCY"), CostMDCY)
            SetTextBoxValue(DBReader("FTEMDVolPY"), FTEMDVolPY)
            SetTextBoxValue(DBReader("CostMDVolPY"), CostMDVolPY)
            SetTextBoxValue(DBReader("FTEMDVolCY"), FTEMDVolCY)
            SetTextBoxValue(DBReader("CostMDVolCY"), CostMDVolCY)
            SetTextBoxValue(DBReader("FTEChapPY"), FTEChapPY)
            SetTextBoxValue(DBReader("CostChapPY"), CostChapPY)
            SetTextBoxValue(DBReader("FTEChapCY"), FTEChapCY)
            SetTextBoxValue(DBReader("CostChapCY"), CostChapCY)
            SetTextBoxValue(DBReader("FTEOtherPY"), FTEOtherPY)
            SetTextBoxValue(DBReader("CostOtherPY"), CostOtherPY)
            SetTextBoxValue(DBReader("FTEOtherCY"), FTEOtherCY)
            SetTextBoxValue(DBReader("CostOtherCY"), CostOtherCY)
            SetTextBoxValue(DBReader("FTENonClinicPY"), FTENonClinicPY)
            SetTextBoxValue(DBReader("CostNonClinicPY"), CostNonClinicPY)
            SetTextBoxValue(DBReader("FTENonClinicCY"), FTENonClinicCY)
            SetTextBoxValue(DBReader("CostNonClinicCY"), CostNonClinicCY)
            SetTextBoxValue(DBReader("FTETotalPY"), FTETotalPY)
            SetTextBoxValue(DBReader("CostTotalPY"), CostTotalPY)
            SetTextBoxValue(DBReader("FTETotalCY"), FTETotalCY)
            SetTextBoxValue(DBReader("CostTotalCY"), CostTotalCY)
            'F8.	CONTRACT PER DIEM - SUPERVISION
            SetTextBoxValue(DBReader("FTEMedDirectorPY"), FTEMedDirectorPY)
            SetTextBoxValue(DBReader("CostMedDirectorPY"), CostMedDirectorPY)
            SetTextBoxValue(DBReader("FTEMedDirectorCY"), FTEMedDirectorCY)
            SetTextBoxValue(DBReader("CostMedDirectorCY"), CostMedDirectorCY)
            SetTextBoxValue(DBReader("FTEAdminPY"), FTEAdminPY)
            SetTextBoxValue(DBReader("CostAdminPY"), CostAdminPY)
            SetTextBoxValue(DBReader("FTEAdminCY"), FTEAdminCY)
            SetTextBoxValue(DBReader("CostAdminCY"), CostAdminCY)
            SetTextBoxValue(DBReader("FTESupervisionTotalPY"), FTESupervisionTotalPY)
            SetTextBoxValue(DBReader("CostSupervisionTotalPY"), CostSupervisionTotalPY)
            SetTextBoxValue(DBReader("FTESupervisionTotalCY"), FTESupervisionTotalCY)
            SetTextBoxValue(DBReader("CostSupervisionTotalCY"), CostSupervisionTotalCY)
        End While
        'DBReader.Close()
        'con.Close()
        'con = Nothing
        'DBReader = Nothing
        costsDB.TerminateDBOperation()
    End Sub

    Sub LoadSurveySectionG()
        'commented code - JS
        'Dim strSQL As String
        'Dim con As New SqlConnection(ConfigurationManager.ConnectionStrings("ConnectionString").ConnectionString)
        'con.Open()
        'strSQL = "Select * FROM Survey where UserName='" & UserName.Text & "'"
        'Dim cmd As New SqlCommand(strSQL, con)
        'Dim DBReader = cmd.ExecuteReader()
        Dim surveyDB As SurveyDBLayer = New SurveyDBLayer()
        Dim DBReader = surveyDB.GetSurveyByUsername(UserName.Text)
        While DBReader.Read()

            If Len(DBReader("MoreFacilities_Inpt") & "") > 0 Then
                lblSectionH.Text = DBReader("MoreFacilities_Inpt")
            End If
            If Len(DBReader("HospMedicarePatients") & "") > 0 Then HospMedicarePatients.Text = DBReader("HospMedicarePatients")
            If Len(DBReader("MedRoutine") & "") > 0 Then MedRoutine.Text = DBReader("MedRoutine")
            If Len(DBReader("MedInpatient") & "") > 0 Then MedInpatient.Text = DBReader("MedInpatient")
            If Len(DBReader("MedRespite") & "") > 0 Then MedRespite.Text = DBReader("MedRespite")
            If Len(DBReader("MedContinuous") & "") > 0 Then MedContinuous.Text = DBReader("MedContinuous")
            If Len(DBReader("HospMedicareDays") & "") > 0 Then HospMedicareDays.Text = DBReader("HospMedicareDays")
            If Len(DBReader("HospMedicaidPatients") & "") > 0 Then HospMedicaidPatients.Text = DBReader("HospMedicaidPatients")
            If Len(DBReader("MediRoutine") & "") > 0 Then MediRoutine.Text = DBReader("MediRoutine")
            If Len(DBReader("MediInpatient") & "") > 0 Then MediInpatient.Text = DBReader("MediInpatient")
            If Len(DBReader("MediRespite") & "") > 0 Then MediRespite.Text = DBReader("MediRespite")
            If Len(DBReader("MediContinuous") & "") > 0 Then MediContinuous.Text = DBReader("MediContinuous")
            If Len(DBReader("HospMedicaidDays") & "") > 0 Then HospMedicaidDays.Text = DBReader("HospMedicaidDays")
            If Len(DBReader("MediMCOPats") & "") > 0 Then MediMCOPats.Text = DBReader("MediMCOPats")
            If Len(DBReader("MediMCORoutine") & "") > 0 Then MediMCORoutine.Text = DBReader("MediMCORoutine")
            If Len(DBReader("MediMCOInpat") & "") > 0 Then MediMCOInpat.Text = DBReader("MediMCOInpat")
            If Len(DBReader("MediMCORespite") & "") > 0 Then MediMCORespite.Text = DBReader("MediMCORespite")
            If Len(DBReader("MediMCOCont") & "") > 0 Then MediMCOCont.Text = DBReader("MediMCOCont")
            If Len(DBReader("MediMCODays") & "") > 0 Then MediMCODays.Text = DBReader("MediMCODays")
            If Len(DBReader("ComServed") & "") > 0 Then ComServed.Text = DBReader("ComServed")

            If Len(DBReader("ComRoutine") & "") > 0 Then ComRoutine.Text = DBReader("ComRoutine")
            If Len(DBReader("ComInpatient") & "") > 0 Then ComInpatient.Text = DBReader("ComInpatient")
            If Len(DBReader("ComRespite") & "") > 0 Then ComRespite.Text = DBReader("ComRespite")
            If Len(DBReader("ComContinuous") & "") > 0 Then ComContinuous.Text = DBReader("ComContinuous")
            If Len(DBReader("ComTot") & "") > 0 Then ComTot.Text = DBReader("ComTot")
            If Len(DBReader("ComNonMCOServed") & "") > 0 Then ComNonMCOServed.Text = DBReader("ComNonMCOServed")
            If Len(DBReader("ComNonMCORoutine") & "") > 0 Then ComNonMCORoutine.Text = DBReader("ComNonMCORoutine")
            If Len(DBReader("ComNonMCOInpatient") & "") > 0 Then ComNonMCOInpatient.Text = DBReader("ComNonMCOInpatient")
            If Len(DBReader("ComNonMCORespite") & "") > 0 Then ComNonMCORespite.Text = DBReader("ComNonMCORespite")
            If Len(DBReader("ComNonMCOContinuous") & "") > 0 Then ComNonMCOContinuous.Text = DBReader("ComNonMCOContinuous")
            If Len(DBReader("ComNonMCOTot") & "") > 0 Then ComNonMCOTot.Text = DBReader("ComNonMCOTot")
            If Len(DBReader("ComMCOServed") & "") > 0 Then ComMCOServed.Text = DBReader("ComMCOServed")
            If Len(DBReader("ComMCORoutine") & "") > 0 Then ComMCORoutine.Text = DBReader("ComMCORoutine")
            If Len(DBReader("ComMCOInpatient") & "") > 0 Then ComMCOInpatient.Text = DBReader("ComMCOInpatient")
            If Len(DBReader("ComMCORespite") & "") > 0 Then ComMCORespite.Text = DBReader("ComMCORespite")
            If Len(DBReader("ComMCOContinuous") & "") > 0 Then ComMCOContinuous.Text = DBReader("ComMCOContinuous")
            If Len(DBReader("ComMCOTot") & "") > 0 Then ComMCOTot.Text = DBReader("ComMCOTot")
            If Len(DBReader("BlueServed") & "") > 0 Then BlueServed.Text = DBReader("BlueServed")
            If Len(DBReader("BlueRoutine") & "") > 0 Then BlueRoutine.Text = DBReader("BlueRoutine")
            If Len(DBReader("BlueInpatient") & "") > 0 Then BlueInpatient.Text = DBReader("BlueInpatient")
            If Len(DBReader("BlueRespite") & "") > 0 Then BlueRespite.Text = DBReader("BlueRespite")
            If Len(DBReader("BlueContinuous") & "") > 0 Then BlueContinuous.Text = DBReader("BlueContinuous")
            If Len(DBReader("BlueTot") & "") > 0 Then BlueTot.Text = DBReader("BlueTot")
            If Len(DBReader("BlueNonMCOServed") & "") > 0 Then BlueNonMCOServed.Text = DBReader("BlueNonMCOServed")
            If Len(DBReader("BlueNonMCORoutine") & "") > 0 Then BlueNonMCORoutine.Text = DBReader("BlueNonMCORoutine")

            If Len(DBReader("BlueNonMCOInpatient") & "") > 0 Then BlueNonMCOInpatient.Text = DBReader("BlueNonMCOInpatient")
            If Len(DBReader("BlueNonMCORespite") & "") > 0 Then BlueNonMCORespite.Text = DBReader("BlueNonMCORespite")
            If Len(DBReader("BlueNonMCOContinuous") & "") > 0 Then BlueNonMCOContinuous.Text = DBReader("BlueNonMCOContinuous")
            If Len(DBReader("BlueNonMCOTot") & "") > 0 Then BlueNonMCOTot.Text = DBReader("BlueNonMCOTot")
            If Len(DBReader("BlueMCOServed") & "") > 0 Then BlueMCOServed.Text = DBReader("BlueMCOServed")
            If Len(DBReader("BlueMCORoutine") & "") > 0 Then BlueMCORoutine.Text = DBReader("BlueMCORoutine")
            If Len(DBReader("BlueMCOInpatient") & "") > 0 Then BlueMCOInpatient.Text = DBReader("BlueMCOInpatient")
            If Len(DBReader("BlueMCORespite") & "") > 0 Then BlueMCORespite.Text = DBReader("BlueMCORespite")
            If Len(DBReader("BlueMCOContinuous") & "") > 0 Then BlueMCOContinuous.Text = DBReader("BlueMCOContinuous")
            If Len(DBReader("BlueMCOTot") & "") > 0 Then BlueMCOTot.Text = DBReader("BlueMCOTot")
            If Len(DBReader("SelfPayPatients") & "") > 0 Then SelfPayPatients.Text = DBReader("SelfPayPatients")
            If Len(DBReader("SelfRoutine") & "") > 0 Then SelfRoutine.Text = DBReader("SelfRoutine")
            If Len(DBReader("SelfInpatient") & "") > 0 Then SelfInpatient.Text = DBReader("SelfInpatient")
            If Len(DBReader("SelfRespite") & "") > 0 Then SelfRespite.Text = DBReader("SelfRespite")
            If Len(DBReader("SelfContinuous") & "") > 0 Then SelfContinuous.Text = DBReader("SelfContinuous")
            If Len(DBReader("SelfPayDays") & "") > 0 Then SelfPayDays.Text = DBReader("SelfPayDays")
            If Len(DBReader("UnChPats") & "") > 0 Then UnChPats.Text = DBReader("UnChPats")
            If Len(DBReader("UnChRoutine") & "") > 0 Then UnChRoutine.Text = DBReader("UnChRoutine")
            If Len(DBReader("UnChInpat") & "") > 0 Then UnChInpat.Text = DBReader("UnChInpat")
            If Len(DBReader("UnChRespite") & "") > 0 Then UnChRespite.Text = DBReader("UnChRespite")
            If Len(DBReader("UnChCont") & "") > 0 Then UnChCont.Text = DBReader("UnChCont")
            If Len(DBReader("UnChDays") & "") > 0 Then UnChDays.Text = DBReader("UnChDays")

            ' Ne 2014----------------------------------------------------------------------
            If Len(DBReader("ChyPats") & "") > 0 Then ChyPats.Text = DBReader("ChyPats")
            If Len(DBReader("ChyRoutine") & "") > 0 Then ChyRoutine.Text = DBReader("ChyRoutine")
            If Len(DBReader("ChyInpat") & "") > 0 Then ChyInpat.Text = DBReader("ChyInpat")
            If Len(DBReader("ChyRespite") & "") > 0 Then ChyRespite.Text = DBReader("ChyRespite")
            If Len(DBReader("ChyCont") & "") > 0 Then ChyCont.Text = DBReader("ChyCont")
            If Len(DBReader("ChyDays") & "") > 0 Then ChyDays.Text = DBReader("ChyDays")

            If Len(DBReader("OtherPatients") & "") > 0 Then OtherPatients.Text = DBReader("OtherPatients")
            If Len(DBReader("OtherRoutine") & "") > 0 Then OtherRoutine.Text = DBReader("OtherRoutine")

            If Len(DBReader("OtherInpatient") & "") > 0 Then OtherInpatient.Text = DBReader("OtherInpatient")
            If Len(DBReader("OtherRespite") & "") > 0 Then OtherRespite.Text = DBReader("OtherRespite")
            If Len(DBReader("OtherContinuous") & "") > 0 Then OtherContinuous.Text = DBReader("OtherContinuous")
            If Len(DBReader("OtherDays") & "") > 0 Then OtherDays.Text = DBReader("OtherDays")
            If Len(DBReader("TotHospPatients") & "") > 0 Then TotHospPatients.Text = DBReader("TotHospPatients")
            If Len(DBReader("LevelRoutine") & "") > 0 Then LevelRoutine.Text = DBReader("LevelRoutine")
            If Len(DBReader("LevelInpatient") & "") > 0 Then LevelInpatient.Text = DBReader("LevelInpatient")
            If Len(DBReader("LevelRespite") & "") > 0 Then LevelRespite.Text = DBReader("LevelRespite")
            If Len(DBReader("LevelContinuous") & "") > 0 Then LevelContinuous.Text = DBReader("LevelContinuous")
            If Len(DBReader("TotHospDays") & "") > 0 Then TotHospDays.Text = DBReader("TotHospDays")
            'If Len(DBReader("HospServRev") & "") > 0 Then HospServRev.Text = DBReader("HospServRev")
            'If Len(DBReader("HospServExp") & "") > 0 Then HospServExp.Text = DBReader("HospServExp")
            'If Len(DBReader("TotAgFundRev") & "") > 0 Then TotAgFundRev.Text = DBReader("TotAgFundRev")
            'If Len(DBReader("TotAgFundExp") & "") > 0 Then TotAgFundExp.Text = DBReader("TotAgFundExp")
            'If Len(DBReader("OtherAgRev") & "") > 0 Then OtherAgRev.Text = DBReader("OtherAgRev")
            'If Len(DBReader("OtherAgExp") & "") > 0 Then OtherAgExp.Text = DBReader("OtherAgExp")
            'If Len(DBReader("OverheadExp") & "") > 0 Then OverheadExp.Text = DBReader("OverheadExp")
            'If Len(DBReader("LLRevenue") & "") > 0 Then LLRevenue.Text = DBReader("LLRevenue")
            'If Len(DBReader("LLExpenses") & "") > 0 Then LLExpenses.Text = DBReader("LLExpenses")

            'G2	REVENUE (PART II) 07/23/2026
            SetTextBoxValue(DBReader("MedicareRevPY"), MedicareRevPY)
            SetTextBoxValue(DBReader("MedicareExpPY"), MedicareExpPY)
            SetTextBoxValue(DBReader("MedicareRevCY"), MedicareRevCY)
            SetTextBoxValue(DBReader("MedicareExpCY"), MedicareExpCY)
            SetTextBoxValue(DBReader("MedicaidRevPY"), MedicaidRevPY)
            SetTextBoxValue(DBReader("MedicaidExpPY"), MedicaidExpPY)
            SetTextBoxValue(DBReader("MedicaidRevCY"), MedicaidRevCY)
            SetTextBoxValue(DBReader("MedicaidExpCY"), MedicaidExpCY)
            SetTextBoxValue(DBReader("InsRevPY"), InsRevPY)
            SetTextBoxValue(DBReader("InsExpPY"), InsExpPY)
            SetTextBoxValue(DBReader("InsRevCY"), InsRevCY)
            SetTextBoxValue(DBReader("InsExpCY"), InsExpCY)
            SetTextBoxValue(DBReader("SelfPayRevPY"), SelfPayRevPY)
            SetTextBoxValue(DBReader("SelfPayExpPY"), SelfPayExpPY)
            SetTextBoxValue(DBReader("SelfPayRevCY"), SelfPayRevCY)
            SetTextBoxValue(DBReader("SelfPayExpCY"), SelfPayExpCY)
            SetTextBoxValue(DBReader("OthGovtRevPY"), OthGovtRevPY)
            SetTextBoxValue(DBReader("OthGovtExpPY"), OthGovtExpPY)
            SetTextBoxValue(DBReader("OthGovtRevCY"), OthGovtRevCY)
            SetTextBoxValue(DBReader("OthGovtExpCY"), OthGovtExpCY)
            SetTextBoxValue(DBReader("TotalHospServRevPY"), TotalHospServRevPY)
            SetTextBoxValue(DBReader("TotalHospServExpPY"), TotalHospServExpPY)
            SetTextBoxValue(DBReader("TotalHospServRevCY"), TotalHospServRevCY)
            SetTextBoxValue(DBReader("TotalHospServExpCY"), TotalHospServExpCY)
            SetTextBoxValue(DBReader("TotalAgFundRevPY"), TotalAgFundRevPY)
            SetTextBoxValue(DBReader("TotalAgFundExpPY"), TotalAgFundExpPY)
            SetTextBoxValue(DBReader("TotalAgFundRevCY"), TotalAgFundRevCY)
            SetTextBoxValue(DBReader("TotalAgFundExpCY"), TotalAgFundExpCY)
            SetTextBoxValue(DBReader("TotalOtherRevPY"), TotalOtherRevPY)
            SetTextBoxValue(DBReader("TotalOtherExpPY"), TotalOtherExpPY)
            SetTextBoxValue(DBReader("TotalOtherRevCY"), TotalOtherRevCY)
            SetTextBoxValue(DBReader("TotalOtherExpCY"), TotalOtherExpCY)
            SetTextBoxValue(DBReader("TotalCharityRevPY"), TotalCharityRevPY)
            SetTextBoxValue(DBReader("TotalCharityExpPY"), TotalCharityExpPY)
            SetTextBoxValue(DBReader("TotalCharityRevCY"), TotalCharityRevCY)
            SetTextBoxValue(DBReader("TotalCharityExpCY"), TotalCharityExpCY)
            SetTextBoxValue(DBReader("TotalStaffEduExpPY"), TotalStaffEduExpPY)
            SetTextBoxValue(DBReader("TotalStaffEduExpCY"), TotalStaffEduExpCY)
            SetTextBoxValue(DBReader("TotalNoInsExpPY"), TotalNoInsExpPY)
            SetTextBoxValue(DBReader("TotalNoInsExpCY"), TotalNoInsExpCY)
            SetTextBoxValue(DBReader("TotalOverExpPY"), TotalOverExpPY)
            SetTextBoxValue(DBReader("TotalOverExpCY"), TotalOverExpCY)
            SetTextBoxValue(DBReader("GrandTotalRevPY"), GrandTotalRevPY)
            SetTextBoxValue(DBReader("GrandTotalExpPY"), GrandTotalExpPY)
            SetTextBoxValue(DBReader("GrandTotalRevCY"), GrandTotalRevCY)
            SetTextBoxValue(DBReader("GrandTotalExpCY"), GrandTotalExpCY)
            'G2-1. FINANCIAL AND OPERATIONAL PERFORMANCE
            SetTextBoxValue(DBReader("FinCashPY"), FinCashPY)
            SetTextBoxValue(DBReader("FinCashCY"), FinCashCY)
            SetTextBoxValue(DBReader("FinTotalRevPY"), FinTotalRevPY)
            SetTextBoxValue(DBReader("FinTotalRevCY"), FinTotalRevCY)
            SetTextBoxValue(DBReader("FinTotalExpPY"), FinTotalExpPY)
            SetTextBoxValue(DBReader("FinTotalExpCY"), FinTotalExpCY)
            SetTextBoxValue(DBReader("FinBadDebtPY"), FinBadDebtPY)
            SetTextBoxValue(DBReader("FinBadDebtCY"), FinBadDebtCY)
            SetTextBoxValue(DBReader("FinNetIncomePY"), FinNetIncomePY)
            SetTextBoxValue(DBReader("FinNetIncomeCY"), FinNetIncomeCY)
            SetTextBoxValue(DBReader("FinDebtCoverRatioPY"), FinDebtCoverRatioPY)
            SetTextBoxValue(DBReader("FinDebtCoverRatioCY"), FinDebtCoverRatioCY)
            SetTextBoxValue(DBReader("FinAdjEBITDAPY"), FinAdjEBITDAPY)
            SetTextBoxValue(DBReader("FinAdjEBITDACY"), FinAdjEBITDACY)
            'G2-2. TOTAL PALLIATIVE CARE REVENUE
            SetTextBoxValue(DBReader("PalMedicareRevPY"), PalMedicareRevPY)
            SetTextBoxValue(DBReader("PalMedicareExpPY"), PalMedicareExpPY)
            SetTextBoxValue(DBReader("PalMedicareRevCY"), PalMedicareRevCY)
            SetTextBoxValue(DBReader("PalMedicareExpCY"), PalMedicareExpCY)
            SetTextBoxValue(DBReader("PalMedicaidRevPY"), PalMedicaidRevPY)
            SetTextBoxValue(DBReader("PalMedicaidExpPY"), PalMedicaidExpPY)
            SetTextBoxValue(DBReader("PalMedicaidRevCY"), PalMedicaidRevCY)
            SetTextBoxValue(DBReader("PalMedicaidExpCY"), PalMedicaidExpCY)
            SetTextBoxValue(DBReader("PalInsRevPY"), PalInsRevPY)
            SetTextBoxValue(DBReader("PalInsExpPY"), PalInsExpPY)
            SetTextBoxValue(DBReader("PalInsRevCY"), PalInsRevCY)
            SetTextBoxValue(DBReader("PalInsExpCY"), PalInsExpCY)
            SetTextBoxValue(DBReader("PalSelfPayRevPY"), PalSelfPayRevPY)
            SetTextBoxValue(DBReader("PalSelfPayExpPY"), PalSelfPayExpPY)
            SetTextBoxValue(DBReader("PalSelfPayRevCY"), PalSelfPayRevCY)
            SetTextBoxValue(DBReader("PalSelfPayExpCY"), PalSelfPayExpCY)
            SetTextBoxValue(DBReader("PalOthGovtRevPY"), PalOthGovtRevPY)
            SetTextBoxValue(DBReader("PalOthGovtExpPY"), PalOthGovtExpPY)
            SetTextBoxValue(DBReader("PalOthGovtRevCY"), PalOthGovtRevCY)
            SetTextBoxValue(DBReader("PalOthGovtExpCY"), PalOthGovtExpCY)
            SetTextBoxValue(DBReader("PalTotalHospServRevPY"), PalTotalHospServRevPY)
            SetTextBoxValue(DBReader("PalTotalHospServExpPY"), PalTotalHospServExpPY)
            SetTextBoxValue(DBReader("PalTotalHospServRevCY"), PalTotalHospServRevCY)
            SetTextBoxValue(DBReader("PalTotalHospServExpCY"), PalTotalHospServExpCY)
            If Len(DBReader("ARDays") & "") > 0 Then ARDays.Text = DBReader("ARDays")

        End While
        'DBReader.Close()
        'con.Close()
        'con = Nothing
        'DBReader = Nothing
        surveyDB.TerminateDBOperation()
    End Sub

    Sub LoadComments()
        'Commented code - JS
        'Dim strSQL As String
        'Dim con As New SqlConnection(ConfigurationManager.ConnectionStrings("ConnectionString").ConnectionString)
        'con.Open()
        'strSQL = "Select * FROM Survey where UserName='" & UserName.Text & "'"
        'Dim cmd As New SqlCommand(strSQL, con)
        'Dim DBReader = cmd.ExecuteReader()
        Dim surveyDB As SurveyDBLayer = New SurveyDBLayer()
        Dim DBReader = surveyDB.GetSurveyByUsername(UserName.Text)
        DBReader.Read()
        If Len(DBReader("Comm1_2") & "") > 0 Then
            comm1_2.Text = DBReader("Comm1_2")
        Else
            comm1_2.Text = "No Comments"
        End If

        If Len(DBReader("Comm2_2") & "") > 0 Then
            comm2_2.Text = DBReader("Comm2_2")
        Else
            comm2_2.Text = "No Suggestions"
        End If

        'DBReader.Close()
        'con.Close()
        'con = Nothing
        'DBReader = Nothing
        'surveyDB.TerminateDBOperation()
    End Sub

    Sub LoadCert()
        'Commented code - JS
        'Dim strSQL As String
        'Dim con As New SqlConnection(ConfigurationManager.ConnectionStrings("ConnectionString").ConnectionString)
        'con.Open()
        'strSQL = "Select * FROM survey where UserName='" & UserName.Text & "'"
        'Dim cmd As New SqlCommand(strSQL, con)
        'Dim DBReader = cmd.ExecuteReader()
        Dim surveyDB As SurveyDBLayer = New SurveyDBLayer()
        Dim DBReader = surveyDB.GetSurveyByUsername(UserName.Text)
        DBReader.Read()
        If DBReader("Certification2") = True Then
            lblCert.Text = FormatDateTime(DBReader("Certification2_Date")) & " by: " & lblFirstname.Text & " " & lblLastName.Text
        Else
            lblCert.Text = "Not Certified and Submitted"
        End If
        'DBReader.Close()
        'con.Close()
        'con = Nothing
        'DBReader = Nothing
        surveyDB.TerminateDBOperation()
    End Sub
    Protected Overrides Sub SetTextBoxValue(ByVal dbReaderValue As Object, ByVal txtBx As TextBox)
        If Not IsDBNull(dbReaderValue) And Len(dbReaderValue & "") > 0 Then
            Dim numericValue As Decimal

            If Decimal.TryParse(dbReaderValue.ToString(), numericValue) Then
                txtBx.Text = numericValue.ToString(currencyFormat)
            Else
                txtBx.Text = dbReaderValue
            End If
        End If
    End Sub
End Class
